# Generated by Django 5.0.4 on 2024-04-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0002_alter_subject_options_rename_name_subject_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание модуля"),
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="courses.module",
                        verbose_name="Контент в модуле",
                    ),
                ),
            ],
        ),
    ]
